import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Rubik } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Providers } from "./providers";
import "@resume/ui/globals.css";
import { Toaster } from "@resume/ui/toaster";
import Navbar from "./components/Navbar";
import { headers } from "next/headers";

const rubik = Rubik({
  subsets: ["latin"], // ✅ fix applied here
});

export const metadata: Metadata = {
  title: {
    template: '%s - Resume builder',
    absolute: 'Resume builder'
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";
  
  const showNavbar = !pathname.includes('/editor') && !pathname.includes('/admin');

  return (
    <html lang="en" suppressHydrationWarning>
      <SessionProvider>
        <Providers>
          <body className={rubik.className}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Toaster />
              {showNavbar && <Navbar />}
              {children}
            </ThemeProvider>
          </body>
        </Providers>
      </SessionProvider>
    </html>
  );
}
