-- CreateTable
CREATE TABLE "scraped_jobs" (
    "id" SERIAL NOT NULL,
    "job_id" TEXT,
    "site" TEXT,
    "job_url" TEXT,
    "job_url_direct" TEXT,
    "title" TEXT,
    "company" TEXT,
    "location" TEXT,
    "date_posted" TIMESTAMP(6),
    "job_type" TEXT,
    "salary_source" TEXT,
    "interval" TEXT,
    "min_amount" DECIMAL,
    "max_amount" DECIMAL,
    "currency" TEXT,
    "is_remote" BOOLEAN,
    "job_level" TEXT,
    "job_function" TEXT,
    "listing_type" TEXT,
    "emails" TEXT,
    "description" TEXT,
    "company_industry" TEXT,
    "company_url" TEXT,
    "company_logo" TEXT,
    "company_url_direct" TEXT,
    "company_addresses" TEXT,
    "company_num_employees" TEXT,
    "company_revenue" TEXT,
    "company_description" TEXT,
    "skills" TEXT,
    "experience_range" TEXT,
    "company_rating" DECIMAL,
    "company_reviews_count" INTEGER,
    "vacancy_count" INTEGER,
    "work_from_home_type" TEXT,

    CONSTRAINT "scraped_jobs_pkey" PRIMARY KEY ("id")
);
