export const jobFunctionKeywords = {
  "Engineering": ["engineer", "engineering", "developer", "development", "programmer", "coding", "software"],
  "Software Engineering": ["software engineer", "software developer", "software development", "programmer", "coding", "full stack", "backend", "frontend"],
  "Frontend Developer": ["frontend", "front-end", "react", "vue", "angular", "javascript", "html", "css", "ui developer", "web developer"],
  "Backend Engineer": ["backend", "back-end", "server", "api", "database", "node", "python", "java", "php", "ruby"],
  "Full Stack Developer": ["full stack", "fullstack", "full-stack", "frontend", "backend", "web developer"],
  "Mobile Developer": ["mobile", "ios", "android", "react native", "flutter", "swift", "kotlin", "mobile app"],
  "DevOps": ["devops", "dev ops", "infrastructure", "deployment", "ci/cd", "docker", "kubernetes", "aws", "cloud"],
  "DevOps Engineer": ["devops engineer", "infrastructure engineer", "deployment engineer", "platform engineer", "cloud engineer"],
  "Site Reliability Engineer": ["sre", "site reliability", "infrastructure", "monitoring", "automation", "performance"],
  "Cloud Engineer": ["cloud", "aws", "azure", "gcp", "infrastructure", "kubernetes", "docker"],
  "Design": ["design", "designer", "creative", "visual", "graphic", "ui", "ux"],
  "Product Design": ["product design", "product designer", "ux", "user experience", "design thinking"],
  "UX Designer": ["ux", "user experience", "interaction design", "usability", "research"],
  "UI Designer": ["ui", "user interface", "visual design", "interface design"],
  "Product Designer": ["product designer", "ux designer", "ui designer", "design"],
  "Graphic Design": ["graphic design", "visual design", "print design", "branding"],
  "Graphic Designer": ["graphic designer", "visual designer", "creative designer"],
  "Visual Designer": ["visual designer", "graphic designer", "creative"],
  "Brand Designer": ["brand designer", "branding", "identity design"],
  "Marketing": ["marketing", "promotion", "advertising", "campaign", "growth"],
  "Digital Marketing": ["digital marketing", "online marketing", "internet marketing", "web marketing"],
  "SEO Specialist": ["seo", "search engine optimization", "sem", "search marketing"],
  "Content Marketer": ["content marketing", "content creator", "copywriter", "content strategist"],
  "Social Media Manager": ["social media", "community manager", "social marketing"],
  "Brand Marketing": ["brand marketing", "branding", "brand manager"],
  "Brand Manager": ["brand manager", "product marketing", "brand strategy"],
  "Marketing Manager": ["marketing manager", "marketing lead", "marketing director"],
  "Growth Marketer": ["growth marketing", "growth hacker", "performance marketing", "acquisition"]
} as const;